package com.zcm.lut.dao;

import com.zcm.lut.pojo.User;
import com.zcm.lut.pojo.UserQuery;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

/**
 * @author ZCM
 */
public interface UserDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_0
     *
     * @mbggenerated
     */
    int countByExample(UserQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_0
     *
     * @mbggenerated
     */
    int deleteByExample(UserQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_0
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_0
     *
     * @mbggenerated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_0
     *
     * @mbggenerated
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_0
     *
     * @mbggenerated
     */
    List<User> selectByExample(UserQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_0
     *
     * @mbggenerated
     */
    User selectByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_0
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") User record, @Param("example") UserQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_0
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") User record, @Param("example") UserQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_0
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_0
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(User record);
}