package com.zcm.lut.pojo;

public class User extends PojoParent{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_0.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_0.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_0.sex
     *
     * @mbggenerated
     */
    private Boolean sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_0.age
     *
     * @mbggenerated
     */
    private Byte age;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_0
     *
     * @mbggenerated
     */
    public User(Long userId, String name, Boolean sex, Byte age) {
        this.userId = userId;
        this.name = name;
        this.sex = sex;
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_0
     *
     * @mbggenerated
     */
    public User() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_0.user_id
     *
     * @return the value of user_0.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_0.user_id
     *
     * @param userId the value for user_0.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_0.name
     *
     * @return the value of user_0.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_0.name
     *
     * @param name the value for user_0.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_0.sex
     *
     * @return the value of user_0.sex
     *
     * @mbggenerated
     */
    public Boolean getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_0.sex
     *
     * @param sex the value for user_0.sex
     *
     * @mbggenerated
     */
    public void setSex(Boolean sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_0.age
     *
     * @return the value of user_0.age
     *
     * @mbggenerated
     */
    public Byte getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_0.age
     *
     * @param age the value for user_0.age
     *
     * @mbggenerated
     */
    public void setAge(Byte age) {
        this.age = age;
    }
}